# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Andrew-Kulpa/clickup-task-creator
description: "Github Action for creating a ClickUp Task"
author: Andrew Kulpa
inputs:
  list_id:
    description: "List ID for where the created task exists"
    required: true
  status:
    description: "Status for the created ask"
    required: true
  github_token:
    description: "Github Auth Token"
    required: true
  clickup_token:
    description: "ClickUp Auth Token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "green"
  icon: "package"
