name: "Pull Request / Issue Task Creator"
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  clickup-task:
    runs-on: ubuntu-latest
    steps:
      - uses: andrew-kulpa/clickup-task-creator@releases/v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          clickup_token: "${{ secrets.CLICKUP_TOKEN }}"
          # https://app.clickup.com/${????}/v/li/${list_id}
          list_id: 21028730
          status: TODO
